var tableauQuestion = [
    {   question : "Si va a 65 mph y se acerca a una zona residencial, debe:",
        propositionA : "Acelears",
        propositionB : "Mantienes la velocidad, y dejas pasar otros vehiculos",
        propositionC : "Bajas la velocidad",
        propositionD : "Mantienes la velocidad",
        reponse : "C"},

    {   question : "Si está girando a la derecha en un semáforo, pero ve un paso de peatones, qué debe hacer",
        propositionA : "Pasas el peaton",
        propositionB : "Pasas si no hay ningun vehiculo cercano",
        propositionC : "Esperas a que el peaton cruze",
        propositionD : "Disparas al peaton y continuas",
        reponse : "C"},

    {   question : "Sin ninguna indicación previa, la velocidad en un área residencial es: __ mph",
        propositionA : "30",
        propositionB : "35",
        propositionC : "40",
        propositionD : "45",
        reponse : "A"},

  {   question : "Antes de cada cambio de carril, debe:",
        propositionA : "Checas tus espejos",
        propositionB : "Checas los puntos ciegos",
        propositionC : "Señalas tus intenciones",
        propositionD : "Todas las siguientes",
        reponse : "D"},

  {   question : "¿Qué nivel de alcohol en sangre se clasifica como conducir en estado de ebriedad?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "¿Cuándo puede continuar conduciendo en un semáforo?",
        propositionA : "Cuando esta verde",
        propositionB : "Cuando no hay nadie en la interseccion",
        propositionC : "Cuando estas en zona de escuela",
        propositionD : "Cuando esta verde / o estas girando en una luz roja",
        reponse : "D"},

  {   question : "Un peatón tiene una señal de no cruzar, ¿qué haces?",
        propositionA : "Lo dejas pasar",
        propositionB : "Observas antes de continuar",
        propositionC : "Le gritas que cruze mas rapido",
        propositionD : "Continuas por que el semaforo esta en verde",
        reponse : "D"},

  {   question : "¿Qué está permitido al adelantar a otro vehículo?",
        propositionA : "Lo sigues de cerca y lo pasas",
        propositionB : "Lo pasas sin salirte de la auto via",
        propositionC : "Conduces al lado contrario para pasarlo",
        propositionD : "Excedes el limite de velocidad",
        reponse : "C"},

  {   question : "Conduce por una carretera que indica una velocidad máxima de 70 mph. La mayoría del tráfico circula a 75 mph, por lo que no debería conducir más rápido que:",
        propositionA : "50 mph",
        propositionB : "25 mph",
        propositionC : "30 mph",
        propositionD : "70 mph",
        reponse : "D"},

  {   question : "Cuando lo adelanta otro vehículo, es importante NO:",
        propositionA : "Bajar la velocidad",
        propositionB : "Mirar los espejos",
        propositionC : "Ver otros conductores",
        propositionD : "Aumentar tu velocidad",
        reponse : "D"},
]
